SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.game_registrations (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    team_id bigint NOT NULL,
    CONSTRAINT game_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELED'::character varying])::text[])))
);

ALTER TABLE public.game_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.game_task_hints (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delay_minutes_from_previous_hint integer NOT NULL,
    order_index integer NOT NULL,
    text character varying(4000) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    task_id bigint NOT NULL
);

ALTER TABLE public.game_task_hints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_task_hints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.game_tasks (
    id bigint NOT NULL,
    answer_key character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    failure_penalty_minutes integer NOT NULL,
    order_index integer NOT NULL,
    riddle_text character varying(4000) NOT NULL,
    time_limit_minutes integer NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL
);

ALTER TABLE public.game_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.game_team_sessions (
    id bigint NOT NULL,
    current_order_index integer NOT NULL,
    finished_at timestamp(6) with time zone,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    total_penalty_minutes integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    current_route_item_id bigint NOT NULL,
    current_task_id bigint NOT NULL,
    game_id bigint NOT NULL,
    route_id bigint NOT NULL,
    team_id bigint NOT NULL,
    current_task_started_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT game_team_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'CANCELED'::character varying])::text[])))
);

ALTER TABLE public.game_team_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_team_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.games (
    id bigint NOT NULL,
    city character varying(120) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(4000) NOT NULL,
    finished_at timestamp(6) with time zone,
    max_team_size integer NOT NULL,
    min_team_size integer NOT NULL,
    registration_ends_at timestamp(6) with time zone,
    registration_starts_at timestamp(6) with time zone,
    starts_at timestamp(6) with time zone,
    status character varying(30) NOT NULL,
    task_failure_penalty_minutes integer NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    organizer_id bigint NOT NULL,
    CONSTRAINT games_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'REGISTRATION_OPEN'::character varying, 'REGISTRATION_CLOSED'::character varying, 'IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'CANCELED'::character varying])::text[])))
);

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team_game_route_items (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    order_index integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    route_id bigint NOT NULL,
    task_id bigint NOT NULL
);

ALTER TABLE public.team_game_route_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_game_route_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team_game_routes (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    team_id bigint NOT NULL
);

ALTER TABLE public.team_game_routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_game_routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team_memberships (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    joined_at timestamp(6) with time zone,
    role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT team_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['CAPTAIN'::character varying, 'MEMBER'::character varying])::text[]))),
    CONSTRAINT team_memberships_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying, 'LEFT'::character varying])::text[])))
);

ALTER TABLE public.team_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.teams (
    id bigint NOT NULL,
    city character varying(120) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    invite_code character varying(32) NOT NULL,
    name character varying(120) NOT NULL,
    captain_id bigint NOT NULL
);

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    account_non_locked boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ORGANIZER'::character varying, 'PARTICIPANT'::character varying])::text[])))
);

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

CREATE TABLE public.verification_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(128) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE public.verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.verification_tokens_id_seq OWNED BY public.verification_tokens.id;

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

ALTER TABLE ONLY public.verification_tokens ALTER COLUMN id SET DEFAULT nextval('public.verification_tokens_id_seq'::regclass);

ALTER TABLE ONLY public.game_registrations
    ADD CONSTRAINT game_registrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game_task_hints
    ADD CONSTRAINT game_task_hints_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game_tasks
    ADD CONSTRAINT game_tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT game_team_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_game_route_items
    ADD CONSTRAINT team_game_route_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_game_routes
    ADD CONSTRAINT team_game_routes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_memberships
    ADD CONSTRAINT team_memberships_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT uk9in08syd61oyydey3f63ai6x9 UNIQUE (invite_code);

ALTER TABLE ONLY public.game_registrations
    ADD CONSTRAINT uk_game_registrations_game_team UNIQUE (game_id, team_id);

ALTER TABLE ONLY public.game_task_hints
    ADD CONSTRAINT uk_game_task_hints_task_order UNIQUE (task_id, order_index);

ALTER TABLE ONLY public.game_tasks
    ADD CONSTRAINT uk_game_tasks_game_order UNIQUE (game_id, order_index);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT uk_game_team_sessions_game_team UNIQUE (game_id, team_id);

ALTER TABLE ONLY public.team_game_route_items
    ADD CONSTRAINT uk_team_game_route_items_route_order UNIQUE (route_id, order_index);

ALTER TABLE ONLY public.team_game_route_items
    ADD CONSTRAINT uk_team_game_route_items_route_task UNIQUE (route_id, task_id);

ALTER TABLE ONLY public.team_game_routes
    ADD CONSTRAINT uk_team_game_routes_game_team UNIQUE (game_id, team_id);

ALTER TABLE ONLY public.team_memberships
    ADD CONSTRAINT uk_team_memberships_team_user UNIQUE (team_id, user_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT verification_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT verification_tokens_token_key UNIQUE (token);

CREATE INDEX idx_game_registrations_game_id ON public.game_registrations USING btree (game_id);

CREATE INDEX idx_game_registrations_status ON public.game_registrations USING btree (status);

CREATE INDEX idx_game_registrations_team_id ON public.game_registrations USING btree (team_id);

CREATE INDEX idx_game_task_hints_order_index ON public.game_task_hints USING btree (order_index);

CREATE INDEX idx_game_task_hints_task_id ON public.game_task_hints USING btree (task_id);

CREATE INDEX idx_game_tasks_game_id ON public.game_tasks USING btree (game_id);

CREATE INDEX idx_game_tasks_order_index ON public.game_tasks USING btree (order_index);

CREATE INDEX idx_game_team_sessions_game_id ON public.game_team_sessions USING btree (game_id);

CREATE INDEX idx_game_team_sessions_status ON public.game_team_sessions USING btree (status);

CREATE INDEX idx_game_team_sessions_team_id ON public.game_team_sessions USING btree (team_id);

CREATE INDEX idx_games_city ON public.games USING btree (city);

CREATE INDEX idx_games_organizer_id ON public.games USING btree (organizer_id);

CREATE INDEX idx_games_starts_at ON public.games USING btree (starts_at);

CREATE INDEX idx_games_status ON public.games USING btree (status);

CREATE INDEX idx_team_game_route_items_order_index ON public.team_game_route_items USING btree (order_index);

CREATE INDEX idx_team_game_route_items_route_id ON public.team_game_route_items USING btree (route_id);

CREATE INDEX idx_team_game_route_items_task_id ON public.team_game_route_items USING btree (task_id);

CREATE INDEX idx_team_game_routes_game_id ON public.team_game_routes USING btree (game_id);

CREATE INDEX idx_team_game_routes_team_id ON public.team_game_routes USING btree (team_id);

CREATE INDEX idx_team_memberships_status ON public.team_memberships USING btree (status);

CREATE INDEX idx_team_memberships_team_id ON public.team_memberships USING btree (team_id);

CREATE INDEX idx_team_memberships_user_id ON public.team_memberships USING btree (user_id);

CREATE INDEX idx_teams_captain_id ON public.teams USING btree (captain_id);

CREATE INDEX idx_teams_city ON public.teams USING btree (city);

CREATE INDEX idx_verification_tokens_user_id ON public.verification_tokens USING btree (user_id);

ALTER TABLE ONLY public.game_task_hints
    ADD CONSTRAINT fk1lx3uy4w7aqu7lr1by582nyrq FOREIGN KEY (task_id) REFERENCES public.game_tasks(id);

ALTER TABLE ONLY public.team_game_routes
    ADD CONSTRAINT fk2s264a3lbmfsj7jagiveronli FOREIGN KEY (game_id) REFERENCES public.games(id);

ALTER TABLE ONLY public.team_game_routes
    ADD CONSTRAINT fk3kng1ln3h804qqxni9wsyvfnv FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.team_game_route_items
    ADD CONSTRAINT fk5mvw2rng5qncm4d8qa5xedqn9 FOREIGN KEY (task_id) REFERENCES public.game_tasks(id);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT fk76cy3a55ctafg9nc46ihvw6kb FOREIGN KEY (route_id) REFERENCES public.team_game_routes(id);

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT fkb7n5vxpixkp6ttpq81wwg1v09 FOREIGN KEY (game_id) REFERENCES public.games(id);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT fkctrxhci7pmovpufj7tx1nf5ay FOREIGN KEY (current_task_id) REFERENCES public.game_tasks(id);

ALTER TABLE ONLY public.team_memberships
    ADD CONSTRAINT fkdageusnomailyetuioxi55gfw FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.team_memberships
    ADD CONSTRAINT fkdqwto3i1w1kxarnesb33ydsms FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT fkg56oi84pxeabeis1scdetnrq0 FOREIGN KEY (current_route_item_id) REFERENCES public.team_game_route_items(id);

ALTER TABLE ONLY public.games
    ADD CONSTRAINT fkg7faxn1hrd78o6vaehwm2c7uq FOREIGN KEY (organizer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.team_game_route_items
    ADD CONSTRAINT fkiqeq82b0v3u8hgkq4qsaeatm4 FOREIGN KEY (route_id) REFERENCES public.team_game_routes(id);

ALTER TABLE ONLY public.game_registrations
    ADD CONSTRAINT fklexua7fbs2gt2g2w7jof77j88 FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.game_team_sessions
    ADD CONSTRAINT fknl17hw6q69iyxccdet0t546uo FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT fknm5gsd12609rk1sdsmo5d9nn4 FOREIGN KEY (captain_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.game_registrations
    ADD CONSTRAINT fkpqut90uqawst5k45sdo8idwva FOREIGN KEY (game_id) REFERENCES public.games(id);

ALTER TABLE ONLY public.game_tasks
    ADD CONSTRAINT fksua6o202dbnqjhrqkqgm7wdrt FOREIGN KEY (game_id) REFERENCES public.games(id);
