CREATE TABLE public.game_chat_messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id bigint NOT NULL,
    team_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    channel character varying(30) NOT NULL,
    text character varying(4000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT game_chat_messages_pkey PRIMARY KEY (id),
    CONSTRAINT game_chat_messages_channel_check CHECK (((channel)::text = ANY ((ARRAY['TEAM'::character varying, 'CAPTAIN_ORGANIZER'::character varying])::text[])))
);

CREATE INDEX idx_game_chat_messages_game_id
    ON public.game_chat_messages USING btree (game_id);

CREATE INDEX idx_game_chat_messages_team_id
    ON public.game_chat_messages USING btree (team_id);

CREATE INDEX idx_game_chat_messages_channel
    ON public.game_chat_messages USING btree (channel);

CREATE INDEX idx_game_chat_messages_created_at
    ON public.game_chat_messages USING btree (created_at);

ALTER TABLE ONLY public.game_chat_messages
    ADD CONSTRAINT fk_game_chat_messages_game
    FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.game_chat_messages
    ADD CONSTRAINT fk_game_chat_messages_team
    FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.game_chat_messages
    ADD CONSTRAINT fk_game_chat_messages_sender
    FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE CASCADE;
